-- CreateEnum
CREATE TYPE "TaskStatus" AS ENUM ('PENDING', 'ON_HOLD', 'IN_PROGRESS', 'UNDER_REVIEW', 'COMPLETED');

-- AlterTable
ALTER TABLE "Task" ADD COLUMN     "status" "TaskStatus" NOT NULL DEFAULT 'PENDING';
